#!/bin/bash
####
## Check Portage
## Copyright 2023 spkg developers, licensed under GPLv2

## Checks portage for updates, an emerge --sync must be ran prior which requires a functioning Gentoo system.
## While this may catch a few upates that check-updates does not, I do not find this to be very respectable.
## When and if spkg gets a following with more than just me who can check for updates, this will be deleted (or if requested)
## Likewise with the check-updates script.

source /etc/spkg.conf
source $INSTALL_PATH/libs/pkg-tools
source $INSTALL_PATH/libs/pkg-utils
GENTOO=${GENTOO:-$1}

echo " * Checking Portage for updates ($GENTOO)"

for cat in $(ls -1 $PKG_DB_DIR); do
	[ ! -d $GENTOO/$cat ] && continue
	for p in $(ls -1 $PKG_DB_DIR/$cat); do
		P=$(DB-getPkg $cat/$p | getLatest)
		PV=$(getVersion $P)
		if [ -d $GENTOO/$cat/$p ]; then
			GV=$(ls -1 $GENTOO/$cat/$p/*.ebuild | grep -Ev "p202|9999|_pre|_rc|_alpha" | sort -V | tail -n1 | sed -e 's,.*/,,' -e 's,.ebuild$,,' -e "s,${p}-,," -e 's,-.*$,,' -e 's,_,,')
			if version_gt $GV $PV; then
				echo -n " ** "
				echo "$cat/$p $PV [$GV]"
#			else
#				echo -n "    "
#				echo "$cat/$p $PV [$GV]"
			fi
		else
			echo "No ebuild for $cat/$p"
		fi
	done
done

