#!/bin/bash

source /etc/spkg.conf
source "${INSTALL_PATH}/libs/pkg-utils"
source "${INSTALL_PATH}/libs/pkg-tools"
source "${INSTALL_PATH}/libs/updatesha1"
source "${INSTALL_PATH}/libs/utils"
source "${INSTALL_PATH}/libs/spkg-include"
source "${INSTALL_PATH}/libs/build-tools"
source "${INSTALL_PATH}/libs/builddefaults"

SRC_URI="https://gentoo.osuosl.org/distfiles/"
DFILES_INDEX="/tmp/distindex"
DFILES=/tmp/DFILES
UPDATE_LIST=/tmp/updatelist

VERBOSE=${VERBOSE:-0}

if [[ $(find "$DFILES_INDEX" -mtime +1 -print) || ! -e $DFILES_INDEX ]]; then
	cd ${DFILES_INDEX%/*}
	wget -O "$DFILES_INDEX" "$SRC_URI"
fi
echo Original: $(cat $DFILES_INDEX | wc -l) entries
grep "href=" $DFILES_INDEX | sed -e 's,.*href="\([^"]*\).*,\1,'> $DFILES
echo URLS: $(cat $DFILES | wc -l) entries

FILTER=("\.patch"
		"\.crate"
		"\.asc"
		"\.sig"
		"\.diff"
		"/"
		"docs-html"
		"\.gem"
		"\-userguide"
		"\-rc[0-9]"
		"\-RC-"
		"\-beta"
		"pre[0-9]"
		"^which"
		"\.9[0-9]"
		"gettext-1"
		"gtk-4"
		"gtksourceview-[45]"
		"lmdb-1"
		"gnupg-2.7"
		"git-4"
		"luit-20"
		"mako-1.7"
		"bash-completion-20"
		"json-20"
		"zstd-[0-9]\.[0-9]\.[0-9]\.[0-9]"
)
for f in ${FILTER[@]}; do
	grep -iv $f $DFILES > ${DFILES}.new
	mv $DFILES{.new,}
done

echo Filtered: $(cat $DFILES | wc -l) entries

for p in $(find $PKG_DB_DIR -mindepth 2 -type d | sed "s,$PKG_DB_DIR/,,"); do
	p=$(echo $p | sed "s,$PKG_DB_DIR/,,")
	PK=$p
	[[ $PK == accounts/* || $PK == spkg* || $PK == virtual/* || $PK == *git/* ]] && continue
#	echo -n "Checking $PK : "
	p=${p#*/}
	# Check Gentoo DFILES for latest versions.

	# Alter the names for filename detection
	case "$p" in
		xz-utils) p=xz ;;
		libpcre) p=pcre- ;;
		libpcre2) p=pcre2 ;;
		libsdl) p=SDL-1 ;;
		libsdl2) p=SDL2 ;;
		llvm) p=llvm-project ;;
		maven-bin) p=apache-maven ;;
		btrfs-progs) p+=-v ;;
		musicbrainz) p=lib$p ;;
		xorg-proto) p=xorgproto ;;
		linux-headers|linux-kernel) p=linux-6 ;;
		lmdb) p=lmdbxx-0 ;;
		cdparanoia) p=cdparanoia-III ;;
		pam) p=Linux-${p^^};;
		xvid) p+=core ;;
		docbook-dtd) p=docbook-4 ;;
		docbook-xsl-nons) p=docbook-xsl ;;
		ghostscript-gpl) p=ghostscript ;;
	esac

	FILES=$(grep -P -i "^$p[-0-9\._]+(src|bin|orig|source)?.(tar|zip|tbz2|tgz)" $DFILES)

	# Get the correct versions
	case "$p" in
		gcc) FILES=$(echo $FILES| tr ' ' '\n' | grep -E -v "202[0-9]{5}" | tail -n2 | head -n1) ;;
		libopenmpt) FILES=$(grep -P -i "^$p-" $DFILES); FILES=${FILES//+release.autotools/} ;;
		ntp|openssh) FILES=$(grep -P "^$p-[0-9p]+" $DFILES | grep -v 'manpages') ;;
		timezone-data) FILES=$(grep -P "tzdata[0-9a-z]{5}" $DFILES) ;;
		unzip) FILES=$(grep -P unzip[0-9]+ $DFILES | sed -e 's,unzip,unzip-,' -e 's,\([0-9]\),\1.,g' -e 's,\.\.,.,') ;;
	esac
	FILE=$(echo $FILES | tr ' ' '\n' | sort -V | tail -n1)
	FILE_O=$FILE
	FILE=$(echo $FILE | sed -E -e 's,(-bin.*|[\.-]src.*|-source.*|\.orig|.tar.*|.tgz|.tbz2|.zip)$,,')


	# Do some package specific modifications here
	case "$p" in
		boost) FILE=${FILE/_/-}; FILE=${FILE//_/.} ;;
		btrfs-progs-v) FILE=${FILE/-v/-} ;;
		lvm2) FILE=$(echo $FILE|sed 's,LVM2\.,lvm2-,') ;;
		tcl) FILE=${FILE/tcl/tcl-} ;;
		timezone-data) FILE=${FILE/tzdata/} ;;
	esac

	# These apply to all packages.
	FILE=${FILE/.orig/}
	FILE=${FILE//_/-}

	PKG=$(DB-getPkgList $PK | fileToList | getLatest | getVersion)
	PKG=${PKG##*/}
	[[ ${FILE##*-} == "" ]] && echo "Checking $PK : $PKG : ${FILE##*-}"
	if [[ ${FILE##*-} == $PKG ]]; then
		continue
	fi
	if [[ $(version_gt ${FILE##*-} $PKG) == 0 ]]; then
#		echo $FILE [ $PK-$PKG ] $FILE_O >> $UPDATE_LIST
		echo " * Updating $PK : $PKG -> ${FILE##*-}" >> $UPDATE_LIST
#		IPKG=$(DB-getPkg $PKG | getLatest)
		setupENV $PK
		cp "$PKG_BLD" "$PKG_DB_DIR/$PK/${FILE##*-}.build"
		sed -e '/ARCH/ s, \([^~]\), ~\1,' \
			-e '/ARCH/ s,="\([^~]\),="~\1,' \
			-i "$PKG_DB_DIR/$PK/${FILE##*-}.build"
		updatesha1 "$PK"
	fi
done
if [ -e $UPDATE_LIST ]; then
	cat $UPDATE_LIST
	rm $UPDATE_LIST
fi
