#!/bin/bash

source /etc/spkg.conf
source $INSTALL_PATH/libs/helpermethods
GENTOO=${GENTOO:-$1}

for cat in $(ls -1 $PKG_DB_DIR); do
	[ ! -d $GENTOO/$cat ] && continue
	for p in $(ls -1 $PKG_DB_DIR/$cat); do
		P=$(getlatestversion $cat/$p)
		PV=$(getpkgver $P)
		if [ -d $GENTOO/$cat/$p ]; then
			GV=$(ls -1 $GENTOO/$cat/$p/*.ebuild | grep -Ev "p202|9999|_pre|_rc|_alpha" | sort -V | tail -n1 | sed -e 's,.*/,,' -e 's,.ebuild$,,' -e "s,${p}-,," -e 's,-.*$,,' -e 's,_,,')
			if version_gt $GV $PV; then
				echo -n " ** "
				echo "$cat/$p $PV [$GV]"
#			else
#				echo -n "    "
#				echo "$cat/$p $PV [$GV]"
			fi
		else
			echo "No ebuild for $cat/$p"
		fi
	done
done

