#!/bin/sh
GENTOO=/srv/media/backup/gentoo/var/db/repos/gentoo
for p in $(ls /var/db/pkg/ -1); do 
	ls -d $GENTOO/*/$p 2>apps-error | 
		sed -e "s,$GENTOO/,,"
done | sort | uniq > apps

#Several Duplicates occur
# Such as ones in acct-{user,group}, virtual, license
# as well as dev-haskell, dev-python/zstd, app-vim
# net-irc, dev-lua
# dev-libs/mpc & media-sound/mpc

echo " * Unresolved Duplicates"
for a in $(cat apps | 
	grep -v '\(acct-\|dev-haskell\|dev-python/zstd\|app-vim\|net-irc\|dev-lua\|media-sound/mpc\|virtual\|license\|dev-ruby\|app-xemacs\)' |
	sed 's,.*/,,' | 
	sort|uniq -d); do 
		grep $a apps
done
for a in $(cat apps | 
	grep -v '\(acct-\|dev-haskell\|dev-python/zstd\|app-vim\|net-irc\|dev-lua\|media-sound/mpc\|virtual\|license\|dev-ruby\|app-xemacs\)'); do 
		grep $a apps
done > apps-filtered

echo " * Making Categories"
for d in $(cat apps-filtered|sed 's,/.*,,' | sort | uniq); do
	[ -d "$d" ] || mkdir -p "$d" && echo -n "."
done; echo

echo " * Making Package Directories"
for d in $(cat apps-filtered | sort | uniq); do
	[ -d "$d" ] || mkdir -p "$d" && echo -n "."
done; echo

echo " * Migrating .build files"
for a in $(cat apps-filtered); do
	echo $a
	d=${a#*/}
	for p in $(ls -1 /var/db/pkg/$d | grep '.build'); do
#		SLOT=$(grep 'SLOT' /var/db/pkg/$d/$p | sed -e 's,.*SLOT="*,,' -e 's,"*,,')
#		echo "$p -> ${p/.build/:${SLOT}.build}"
#		grep -v "SLOT" /var/db/pkg/$d/$p > /var/db/spkg/$a/${p/.build/:${SLOT}.build}
		echo /var/db/pkg/$d/$p /var/db/spkg/$a/$p
		cp /var/db/pkg/$d/$p /var/db/spkg/$a/$p
	done
done
