#!/bin/bash

## Enable Debug
#set -x
#export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

source /etc/spkg.conf
source "${INSTALL_PATH}/libs/pkg-utils"
source "${INSTALL_PATH}/libs/pkg-tools"
source "${INSTALL_PATH}/libs/updatesha1"
source "${INSTALL_PATH}/libs/utils"
source "${INSTALL_PATH}/libs/build-tools"
source "${INSTALL_PATH}/libs/builddefaults"

VERBOSE=${VERBOSE:-0}
PKG=$(DB-getPkg $(EntryParser $1) | getLatest)
ver=$2
setPkgENV $PKG
if [[ $PKG_VR == $ver ]]; then
	echo "Nothing to update"
	exit
fi
echo "Update $PKG_CAT/$PKG_NVR to $ver"

## Take the most recent version and make the supplied version.
	sed -e '/ARCHS/ s,\( \|="\)\([^~]\),\1~\2,g' \
		"$(getBldFile $PKG)" > "$PKG_DB_DIR/$PKG_CAT/$PKG_NAME/$ver.build"
	updatesha1 $PKG_CAT/$PKG_NAME
