#!/bin/bash

## Enable Debug
#set -x
#export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

source /etc/spkg.conf
source "${INSTALL_PATH}/libs/pkg-utils"
source "${INSTALL_PATH}/libs/pkg-tools"
source "${INSTALL_PATH}/libs/updatesha1"
source "${INSTALL_PATH}/libs/utils"
source "${INSTALL_PATH}/libs/build-tools"
source "${INSTALL_PATH}/libs/builddefaults"

export NORMAL=$(tput sgr0)
export GREEN=$(tput setaf 82)
export BRIGHT_RED=$(tput setaf 9)
export BRIGHT_YELLOW=$(tput setaf 11)
export IMPORTANT="$BRIGHT_YELLOW!!$NORMAL"
export DIALOG_ERROR="$BRIGHT_RED!!$NORMAL"

VERBOSE=${VERBOSE:-0}
PKG=$(DB-getPkg $(EntryParser $1) | getLatest)
if [[ $PKG == '' || -z $PKG ]]; then
	die " $DIALOG_ERROR Cannot add update: $1 not found!"
fi
ver=$2
setPkgENV $PKG 2>&1 /dev/null
if [[ $PKG_VR == $ver ]] || version_gt $PKG_VR $ver; then
	die " $IMPORTANT Nothing to update, $PKG_NVR is available"
fi
echo " $GREEN*$NORMAL Update $PKG_CAT/$PKG_NVR to $ver"

## Take the most recent version and make the supplied version.
	sed -e '/ARCHS/ s,\( \|="\)\([^~]\),\1~\2,g' \
		"$(getBldFile $PKG)" > "$PKG_DB_DIR/$PKG_CAT/$PKG_NAME/$ver.build"
	updatesha1 $PKG_CAT/$PKG_NAME
