#!/bin/bash
TMPFILE=/tmp/depcheck
[ -e $TMPFILE ] && rm $TMPFILE
source /etc/spkg.conf

search_dependencies() {
	IFS=':' read -r -a search_dirs <<< "$LD_LIBRARY_PATH:$PATH"
	for p in "${search_dirs[@]}"; do
		echo "Searching $p"
		find "$p" -type f 2>/dev/null | while IFS= read -r f; do
			FILE=$(ldd "$f" 2> /dev/null | grep 'not found' | sed -e 's,^\s*,,' -e 's, =>.*,,')
			if [ ! -z "$FILE" ]; then
				IFS=' ';
				for a in "$FILE"; do
					echo $a
				done
				>&2 grep -l "$f" ${PKG_CACHE}/*/*/*/CONTENTS
			fi
		done | sort | uniq
	done 2> >(sed -e "s,${PKG_CACHE%/}/,," -e 's,/[^/]*/CONTENTS,,' | sort | uniq > $TMPFILE)
}

>&2 search_dependencies
>&2 echo
if [ -s "$TMPFILE" ]; then
	>&2 echo "Packages to rebuild"
	cat $TMPFILE
	rm $TMPFILE
else
	>&2 echo "No issues found"
fi
