#!/bin/bash
## Read Latest Log
## Copyright 2023-2025 spkg developers, licensed under GPLv2
## Used to read the latest log or list logs of a given package

LIST=0
PIPE=0
VERSION=0.2
LOG=

source /etc/spkg.conf

die() { echo "$*" 1>&2 ; exit 1; }

parse_cmdline() {
	# Referenced mozilla-launcher script.
	while [ $# -ne 0 ] ; do
		case "${1#-}" in
			l|-list)
				LIST=1
				shift ;;
			p|-pipe)
				PIPE=1
				shift ;;
			h|-help)
				echo "readlatestlog $VERSION by smileaf"
				echo "Usage: $0 [Arguments] [Log Search]"
				echo " Options:"
				echo "  --list, -l      List only"
				echo "  --pipe, -p		Outputs the log which can be piped to something else"
				exit $? ;;
			*)
				LOG="$@"
				break ;;
		esac
	done
}

find_logs() {
	find * -iwholename "*$LOG[/-]*"
}

if [ ! -d "$LOGDIR" ]; then
	mkdir -p "$LOGDIR" || die "Failed to create: LOGDIR: $LOGDIR"
fi
#test -w $LOGDIR || die "Cannot write to LOGDIR: $LOGDIR"

parse_cmdline "$@"

cd $LOGDIR
if [ "$LIST" -eq 1 ]; then
	find_logs | sort -k2 -t- -V -r | uniq -s9
else
	LOGFILE=$(find_logs | sort -V | tail -n1)
	echo "LOGFILE: $LOGFILE ($LOG)"
	if [ -z $LOGFILE ]; then
		echo " ! Log not found!"
		exit 1
	fi
	if [ $PIPE == 1 ]; then
		if [[ $LOGFILE == *.xz ]]; then
			xzcat $LOGFILE 2> /dev/null
		else
			cat $LOGFILE 2> /dev/null
		fi
	else
		xzless $LOGFILE 2> /dev/null
	fi
fi
